<?php

/**
 * @file
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\pathauto_custom_punctuation_test\Hook\PathautoCustomPunctuationTestHooks;

/**
 * Implements hook_pathauto_punctuation_chars_alter().
 */
#[LegacyHook]
function pathauto_custom_punctuation_test_pathauto_punctuation_chars_alter(array &$punctuation) {
  \Drupal::service(PathautoCustomPunctuationTestHooks::class)->pathautoPunctuationCharsAlter($punctuation);
}
